### ISSUE TITLE
url_filter_credential_submission' is undefined

### ISSUE THREAD

**Issue by jmaclean33** [scotchoaf/cis-benchmark-prototype#2]
URL Filter creds are set to default.... issue happened both on API panos 10 and 9.x xml offline

Exception caught: 'ssh_https_snmp_enabled_profiles_no_ip_list'
Exception caught: 'security_rules_with_group_without_wf_names'
Exception caught: 'security_rules_with_group_without_virus_names'
Exception caught: 'security_rules_with_group_without_spyware_names'
Exception caught: 'security_rules_with_group_without_vulnerability_names'
Exception caught: 'security_rules_with_group_without_urlfiltering_names'
Exception caught: 'security_rules_with_group_without_datafiltering_names'
Exception caught: 'zones_with_syn_flooding_names'
Exception caught: 'zones_with_all_flooding_names'
Exception caught: 'zones_with_reconn_enabled_names'
Exception caught: 'zones_with_pkt_attack_enabled_names'
Exception caught: 'url_filter_credential_submission'
'url_filter_credential_submission' is undefined
Exception caught: 'any_any_policies_names'
Exception caught: 'service_any_policies_names'
Internal Server Error: /panhandler/validate-results
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/cnc/pan_cnc/views.py", line 105, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/src/panhandler/views.py", line 821, in get
    return self.form_valid(form)
  File "/app/src/panhandler/views.py", line 980, in form_valid
    skillet_output = skillet.execute(jinja_context)
  File "/usr/local/lib/python3.6/site-packages/skilletlib/skillet/base.py", line 293, in execute
    return self.get_results()
  File "/usr/local/lib/python3.6/site-packages/skilletlib/skillet/pan_validation.py", line 100, in get_results
    context[snippet_name]['output_message'] = s.render(fail_message, context)
  File "/usr/local/lib/python3.6/site-packages/skilletlib/snippet/base.py", line 312, in render
    return t.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1045, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 787, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 461, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'url_filter_credential_submission' is undefined
[30/Nov/2020 15:26:33] "GET /panhandler/validate-results HTTP/1.1" 500 341516

**Comment by ghost** [comment]
Hey Jeff,

When you get a second can you reach out to on slack? I'll need the configuration to recreate the issue and test a fix, thanks.

**Comment by ghost** [comment]
False positive, this can be closed.

**Comment by scotchoaf** [comment]
panHandler version issue
